// src/auth/permissionResolver.js

const ROLES = require("./roles");
const PERMISSIONS = require("./permissions");

const rolePermissions = {
  [ROLES.IAM_SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.IAM_ADMIN]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.USER_DEACTIVATE,

    PERMISSIONS.GROUP_VIEW,
    PERMISSIONS.GROUP_CREATE,
    PERMISSIONS.GROUP_UPDATE,
    PERMISSIONS.GROUP_ASSIGN,

    PERMISSIONS.APP_VIEW,
    PERMISSIONS.APP_ASSIGN,

    PERMISSIONS.AUDIT_VIEW,

    PERMISSIONS.MFA_VIEW,
    PERMISSIONS.MFA_RESET,
  ],

  [ROLES.IAM_AUDITOR]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.GROUP_VIEW,
    PERMISSIONS.APP_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ACCESS_REQUEST_VIEW,
  ],

  [ROLES.IAM_MANAGER]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ACCESS_REQUEST_VIEW,
    PERMISSIONS.ACCESS_REQUEST_APPROVE,
    PERMISSIONS.ACCESS_REQUEST_REJECT,
  ],

  [ROLES.IAM_USER]: [
    PERMISSIONS.ACCESS_REQUEST_CREATE,
    PERMISSIONS.ACCESS_REQUEST_VIEW,
    PERMISSIONS.MFA_VIEW,
  ],
};

const getPermissionsByRole = (role) => {
  return rolePermissions[role] || [];
};

module.exports = {
  getPermissionsByRole,
};