// src/auth/permissions.js

const PERMISSIONS = {
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_SUSPEND: "USER_SUSPEND",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_DELETE: "USER_DELETE",

  GROUP_VIEW: "GROUP_VIEW",
  GROUP_CREATE: "GROUP_CREATE",
  GROUP_UPDATE: "GROUP_UPDATE",
  GROUP_ASSIGN: "GROUP_ASSIGN",

  APP_VIEW: "APP_VIEW",
  APP_ASSIGN: "APP_ASSIGN",

  AUDIT_VIEW: "AUDIT_VIEW",

  ACCESS_REQUEST_CREATE: "ACCESS_REQUEST_CREATE",
  ACCESS_REQUEST_VIEW: "ACCESS_REQUEST_VIEW",
  ACCESS_REQUEST_APPROVE: "ACCESS_REQUEST_APPROVE",
  ACCESS_REQUEST_REJECT: "ACCESS_REQUEST_REJECT",

  MFA_VIEW: "MFA_VIEW",
  MFA_RESET: "MFA_RESET",
};

module.exports = PERMISSIONS;